[workspace]
resolver = "2"
members = [
    "public-user-event",
    "public-account-event",
    "server",
    "shared",
]

[workspace.dependencies]
#horfimbor-eventsource = "0.3"
horfimbor-eventsource ={path = "../horfimbor-engine/horfimbor-eventsource"}
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
eventstore = "4.0.0"
redis = { version = "0.28", features = ["tokio-rustls-comp"] }
uuid = { version = "1.8", features = ["v4", "v5"] }

# TODO move out
public-user-event = { path = "public-user-event", features = ["server"] }
public-account-event = { path = "public-account-event", features = ["server"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "warn"
