[workspace]
resolver = "2"
members = [ "auth-public-event",
    "server", "shared",
]

[workspace.dependencies]
horfimbor-eventsource = "0.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
eventstore = "3.0"
redis= { version = "0.26", features = ["tokio-rustls-comp"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "warn"
