[workspace]
resolver = "2"
members = [ "auth-public-event",
    "server", "shared",
]

[workspace.dependencies]
#horfimbor-eventsource = "0.3"
#horfimbor-eventsource ={path = "../horfimbor-engine/horfimbor-eventsource"}
horfimbor-eventsource ={ git = "https://github.com/horfimbor/horfimbor-engine.git" , branch = "release-plz-2024-10-13T15-44-09Z"}
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
eventstore = "3.0"
redis= { version = "0.27", features = ["tokio-rustls-comp"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "warn"
