[package]
name = "hfb-auth-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
dotenvy = "0.15"
eventstore.workspace = true
jsonwebtoken = "9.3"
redis.workspace = true
rocket = { version = "0.5", features = ["secrets"] }
rocket_cors = "0.6"
uuid = { workspace = true }
serde = "1.0"
serde_json = "1.0"
hfb-auth-shared = { path = "../shared"}
horfimbor-eventsource = { workspace = true }
argon2 = "0.5"
url = { version = "2.5", features = ["serde"] }
futures = "0.3"
public-account-event = {workspace = true }
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
signal-hook = "0.3"
chrono = { workspace = true }
rand = { workspace = true }
horfimbor-jwt = { workspace = true }
ring = "0.17.9"

[dependencies.rocket_dyn_templates]
version = "0.2"
features = ["tera"]

[profile.dev.package.sqlx-macros]
opt-level = 3

[lints]
workspace = true
