[package]
name = "hfb-auth-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
dotenvy = "0.15.7"
eventstore.workspace = true
jsonwebtoken = "9.3.0"
redis.workspace = true
rocket ={ version = "0.5.0" }
rocket_cors = "0.6.0"
sqlx = { version = "0.8.0", features = [ "runtime-tokio-rustls", "mysql", "migrate" ] }
uuid = { version = "1.8.0", features = ["v4", "v5"] }
serde = "1.0.197"
hfb-auth-shared= {path = "../shared", features = ["server"]}
horfimbor-eventsource = {workspace = true}

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["handlebars", "tera"]

[profile.dev.package.sqlx-macros]
opt-level = 3

[lints]
workspace = true