[package]
name = "hfb-auth-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
horfimbor-eventsource = { workspace = true }
serde.workspace = true
thiserror.workspace = true
public-user-event = {workspace = true }
public-account-event = {workspace = true }
chrono = { workspace = true }
url = { version= "2.5", features = ["serde"] }
rand = { workspace = true }
lazy_static = "1.5.0"

[lints]
workspace = true
