[package]
name = "hfb-auth-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
horfimbor-eventsource = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true
auth-public-event = {path = "../auth-public-event"}
chrono = { version = "0.4", features = ["serde"] }

[features]
server = ["horfimbor-eventsource", "auth-public-event/server"]

[lints]
workspace = true
