[package]
name = "hfb-auth-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
horfimbor-eventsource = { workspace = true }
serde.workspace = true
thiserror.workspace = true
public-user-event = {workspace = true }
public-account-event = {workspace = true }
chrono = { version = "0.4", features = ["serde"] }
url = { version= "2.5", features = ["serde"] }
rand = "0.9"

[lints]
workspace = true
