[package]
name = "public-account-event"
version = "0.1.0"
edition = "2021"

[dependencies]
horfimbor-eventsource = { workspace = true, optional = true }
serde.workspace = true
uuid = { version = "1.8", features = ["v4", "v5"] }

[features]
server = ["horfimbor-eventsource"]

[lints]
workspace = true
